spring:
  datasource:
    url: jdbc:sqlserver://hackathonvoicerecorder.database.windows.net:1433;database=voicerecorder;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: Pradeepg21
    password: Nov@212905
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
